<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar Eliminación de Tarea</title>
</head>
<body>
    <div>
        <h1>¿Estás seguro de eliminar esta tarea?</h1>
        <p>Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar esta tarea?</p>
        <div>
            <form method="post">
                <input type="hidden" name="id" value="<?php echo $id; ?>">
                <button type="submit" name="confirm_delete">Eliminar</button>
            </form>
            <a href="index">Cancelar</a>
        </div>
    </div>
</body>
</html>