<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Task List</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <?php
    $allTask = $this->task;
    //print_r($listTasks);
    ?>
    <body action="/controllers/ApplicationController.php">
        <h2>Task Manager</h2>

        <div>
            <a href="create">Create new task</a>
        </div>

        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Creation Date</th>
                    <th>End Date</th>
                    <th>Author</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->allTasks !== null): ?>
                    <?php foreach ($this->allTasks as $task): ?>
                        <tr>
                            <td><?php echo $task['id']; ?></td>
                            <td><?php echo $task['description']; ?></td>
                            <td><?php echo $task['status']; ?></td>
                            <td><?php echo htmlspecialchars($task['date_ini']); ?></td>
                            <td><?php echo $task['date_end']; ?></td>
                            <td><?php echo htmlspecialchars($task['user']); ?></td>
                            <td>
                                <a href="read?id=<?php echo $task['id']; ?>" name="read">Leer</a>
                                <a href="update?id=<?php echo $task['id']; ?>" name="update">Actualizar</a>
                                <a href="delete?id=<?php echo $task['id']; ?>">Borrar</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="7">
                            <p>No tasks available</p>
                        </td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </body>
</html>